# Generated by Django 3.1.4 on 2020-12-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
    ]
